Service name: fairdata-download

diff --git a/legacy-metrics/generate-reports b/legacy-metrics/generate-reports
--- a/legacy-metrics/generate-reports
+++ b/legacy-metrics/generate-reports
@@ -15,12 +15,12 @@ ROOT=`dirname "$METRICS"`
 
 #--------------------------------------------------------------------------------
 
-if [ -z "$DOWNLOAD_SERVICE_SETTINGS" ]; then
-    DOWNLOAD_SERVICE_SETTINGS="$ROOT/dev_config/settings.cfg"
+if [ -z "$DOWNLOAD_SETTINGS" ]; then
+    DOWNLOAD_SETTINGS="$ROOT/dev_config/settings.cfg"
 fi
 
-if [ ! -f "$DOWNLOAD_SERVICE_SETTINGS" ]; then
-    echo "Could not find service configuration file '${DOWNLOAD_SERVICE_SETTINGS}'! Exiting" >&2
+if [ ! -f "$DOWNLOAD_SETTINGS" ]; then
+    echo "Could not find service configuration file '${DOWNLOAD_SETTINGS}'! Exiting" >&2
     exit 1
 fi
 
@@ -34,7 +34,7 @@ if [ ! -f "$EVENTS_SNAPSHOT_FILE" ]; then
 fi
 
 source $ROOT/venv/bin/activate
-source $DOWNLOAD_SERVICE_SETTINGS
+source $DOWNLOAD_SETTINGS
 
 EVENTS_REPORT_ROOT="$METRICS/reports"
 
diff --git a/legacy-metrics/publish-events b/legacy-metrics/publish-events
--- a/legacy-metrics/publish-events
+++ b/legacy-metrics/publish-events
@@ -12,12 +12,12 @@ ROOT=`dirname "$METRICS"`
 
 #--------------------------------------------------------------------------------
 
-if [ -z "$DOWNLOAD_SERVICE_SETTINGS" ]; then
-    DOWNLOAD_SERVICE_SETTINGS="$ROOT/dev_config/settings.cfg"
+if [ -z "$DOWNLOAD_SETTINGS" ]; then
+    DOWNLOAD_SETTINGS="$ROOT/dev_config/settings.cfg"
 fi
 
-if [ ! -f "$DOWNLOAD_SERVICE_SETTINGS" ]; then
-    echo "Could not find service configuration file '${DOWNLOAD_SERVICE_SETTINGS}'! Exiting" >&2
+if [ ! -f "$DOWNLOAD_SETTINGS" ]; then
+    echo "Could not find service configuration file '${DOWNLOAD_SETTINGS}'! Exiting" >&2
     exit 1
 fi
 
@@ -31,7 +31,7 @@ if [ ! -f "$EVENTS_SNAPSHOT_FILE" ]; then
 fi
 
 source $ROOT/venv/bin/activate
-source $DOWNLOAD_SERVICE_SETTINGS
+source $DOWNLOAD_SETTINGS
 
 if [ -z "$FDWE_API" ]; then
     echo "The variable 'FDWE_API' is not defined! Exiting" >&2
